"""Initial revision

Revision ID: 2d4e172e89bf
Revises: 
Create Date: 2025-12-11 20:54:16.440326

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4e172e89bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscriptions',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('events', sa.JSON(), nullable=True),
        sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('timeout_seconds', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('uuid'),
        schema='public'
    )
    op.create_table('work_centers',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('author', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('identifier', name='uq_work_center_identifier'),
        sa.UniqueConstraint('uuid'),
        schema='public'
    )
    op.create_index('idx_work_center_identifier', 'work_centers', ['identifier'], unique=False, schema='public')
    op.create_table('batches',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_closed', sa.Boolean(), nullable=False),
        sa.Column('closed_at', sa.DateTime(), nullable=True),
        sa.Column('task_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('work_center_id', sa.Uuid(), nullable=False),
        sa.Column('shift', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('batch_number', sa.Integer(), nullable=False),
        sa.Column('batch_date', sa.Date(), nullable=False),
        sa.Column('nomenclature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ekn_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('shift_start_time', sa.DateTime(), nullable=False),
        sa.Column('shift_end_time', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['work_center_id'], ['public.work_centers.uuid'], ),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('uuid'),
        schema='public'
    )
    op.create_index('idx_batch_date', 'batches', ['batch_date'], unique=False, schema='public')
    op.create_index('idx_batch_number', 'batches', ['batch_number'], unique=False, schema='public')
    op.create_index('idx_batch_number_date', 'batches', ['batch_number', 'batch_date'], unique=False, schema='public')
    op.create_table('webhook_deliveries',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('event_type', sa.Enum('BATCH_CREATED', 'BATCH_CLOSED', name='webhookeventtype'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='webhookstatus'), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('response_status', sa.Integer(), nullable=True),
        sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('subscription_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['subscription_id'], ['public.webhook_subscriptions.uuid'], ),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('uuid'),
        schema='public'
    )
    op.create_table('products',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('unique_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('batch_id', sa.Uuid(), nullable=False),
        sa.Column('is_aggregated', sa.Boolean(), nullable=False),
        sa.Column('aggregated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['batch_id'], ['public.batches.uuid'], ),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('unique_code', name='uq_product_unique_code'),
        sa.UniqueConstraint('uuid'),
        schema='public'
    )
    op.create_index('idx_product_batch_id', 'products', ['batch_id'], unique=False, schema='public')
    op.create_index('idx_product_is_aggregated', 'products', ['is_aggregated'], unique=False, schema='public')
    op.create_index('idx_product_unique_code', 'products', ['unique_code'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_unique_code', table_name='products', schema='public')
    op.drop_index('idx_product_is_aggregated', table_name='products', schema='public')
    op.drop_index('idx_product_batch_id', table_name='products', schema='public')
    op.drop_table('products', schema='public')
    op.drop_table('webhook_deliveries', schema='public')
    op.execute("DROP TYPE IF EXISTS webhookeventtype")
    op.execute("DROP TYPE IF EXISTS webhookstatus")
    op.drop_index('idx_batch_number_date', table_name='batches', schema='public')
    op.drop_index('idx_batch_number', table_name='batches', schema='public')
    op.drop_index('idx_batch_date', table_name='batches', schema='public')
    op.drop_table('batches', schema='public')
    op.drop_index('idx_work_center_identifier', table_name='work_centers', schema='public')
    op.drop_table('work_centers', schema='public')
    op.drop_table('webhook_subscriptions', schema='public')
    # ### end Alembic commands ###
